version: "3.8"
services:
  silverstripe:
    build:
      context: ./
      dockerfile: Dockerfile
    image: {SS_IMAGE_START}
    ports:
       - 8080:80
    volumes:
       - .:/var/www/html
       - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    depends_on:
       - database
    environment:
       - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
       - DOCUMENT_ROOT=/var/www/html
       - SS_TRUSTED_PROXY_IPS=*
       - SS_ENVIRONMENT_TYPE=dev
       - SS_DATABASE_SERVER=database
       - SS_DATABASE_NAME={SS_DATABASE_NAME}
       - SS_DATABASE_USERNAME=root
       - SS_DATABASE_PASSWORD=
       - SS_DEFAULT_ADMIN_USERNAME=irxadmin
       - SS_DEFAULT_ADMIN_PASSWORD=irxadmin
  database:
    image: mariadb:latest
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
       - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
       - 9191:80
    environment:
       - MYSQL_USERNAME=root
       - MYSQL_ROOT_PASSWORD=
       - PMA_HOST=database
volumes:
     db-data:
