#!/usr/bin/env bash
export APP_PORT=${APP_PORT:-80}
export MYSQL_PORT=${MYSQL_PORT:-3306}

# Create base docker-compose command to run
COMPOSE="docker-compose -f docker-compose.yml"

# If we pass any arguments...
if [ $# -gt 0 ]; then
    if [ "$1" == "init" ]; then
        echo "TITANIC: Initializing Titanic..."

        if [ -f "docker-compose-example.yml" ]; then
            echo "You are missing the docker-compose-example.yml file. Please readd this to your project."
        fi
        if [ -f "Dockerfile-example" ]; then
            echo "You are missing the Dockerfile-example file. Please readd this to your project."
        fi

        PS3="Please select which PHP version this project runs from the above list: "

        select phpversion in 5.6 7.0 7.1 7.2 7.3 7.4
        do
            echo "You selected PHP $phpversion"
            break;
        done

        echo "Please enter a name for the database (no spaces or special characters):"
        read DATABASE_NAME  

        echo "The database will be called: $DATABASE_NAME"

        # Refresh docker-compose.yml from scratch
        cp ./docker-compose-example.yml ./docker-compose.yml
        echo "Refreshing docker-compose.yml..."
        # Refresh Dockerfile from scratch
        cp ./Dockerfile-example ./Dockerfile
        echo "Refreshing Dockerfile..."

        # Retrieve PHP docker image depending on argument and replace variable
        echo "Retrieving PHP docker image..."
        if [[ $phpversion = '7.0' ]]; then
            sed -i '' 's/{SS_IMAGE_START}/brettt89\/silverstripe-web:7.0-apache/g' ./docker-compose.yml
            sed -i '' 's/{SILVERSTRIPE_IMAGE}/brettt89\/silverstripe-web:7.0-apache/g' ./Dockerfile
        elif [[ $phpversion = '7.1' ]]; then
            sed -i '' 's/{SS_IMAGE_START}/brettt89\/silverstripe-web:7.1-apache/g' ./docker-compose.yml
            sed -i '' 's/{SILVERSTRIPE_IMAGE}/brettt89\/silverstripe-web:7.1-apache/g' ./Dockerfile
        elif [[ $phpversion = '7.2' ]]; then
            sed -i '' 's/{SS_IMAGE_START}/brettt89\/silverstripe-web:7.2-apache/g' ./docker-compose.yml
            sed -i '' 's/{SILVERSTRIPE_IMAGE}/brettt89\/silverstripe-web:7.2-apache/g' ./Dockerfile
        elif [[ $phpversion = '7.3' ]]; then
            sed -i '' 's/{SS_IMAGE_START}/brettt89\/silverstripe-web:7.3-apache/g' ./docker-compose.yml
            sed -i '' 's/{SILVERSTRIPE_IMAGE}/brettt89\/silverstripe-web:7.3-apache/g' ./Dockerfile
        elif [[ $phpversion = '7.4' ]]; then
            sed -i '' 's/{SS_IMAGE_START}/brettt89\/silverstripe-web:7.4-apache/g' ./docker-compose.yml
            sed -i '' 's/{SILVERSTRIPE_IMAGE}/brettt89\/silverstripe-web:7.4-apache/g' ./Dockerfile
        elif [[ $phpversion = '5.6' ]]; then
            sed -i '' 's/{SS_IMAGE_START}/brettt89\/silverstripe-web:5.6-apache/g' ./docker-compose.yml
            sed -i '' 's/{SILVERSTRIPE_IMAGE}/brettt89\/silverstripe-web:5.6-apache/g' ./Dockerfile
        fi

        # Use provided database name
        sed -i '' "s/{SS_DATABASE_NAME}/$DATABASE_NAME/g" ./docker-compose.yml

        echo "TITANIC: Making titanic command available"
        chmod +x titanic

        echo "TITANIC: Rebuilding Image..."
        $COMPOSE build
        echo "TITANIC: Finished rebuilding Image..."
        

        # Removing example files
        echo "TITANIC: Almost done... removing example files"
        if [ -f "docker-compose-example.yml" ]; then
            rm docker-compose-example.yml
        fi
        if [ -f "Dockerfile-example" ]; then
            rm Dockerfile-example
        fi
        echo "TITANIC: Finished cleaning up files"

        echo ""
        echo "TITANIC: Power Up Complete!"
        echo "TITANIC: You can now use Titanic"
        echo "TITANIC: Try starting it:"
        echo "./titanic start"

    # Start up containers
    elif [ "$1" == "start" ]; then
        shift 1
        $COMPOSE up -d

    # Stop the containers
    elif [ "$1" == "stop" ]; then
        shift 1
        $COMPOSE down

    # If "composer" is used, pass-thru to "composer"
    # inside a new container
    elif [ "$1" == "composer" ] || [ "$1" == "comp" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            silverstripe \
            ssh-add -l && composer "$@"
    elif [ "$1" == "composer1" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            silverstripe \
            ssh-add -l && composer1 "$@"
    elif [ "$1" == "composer2" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            silverstripe \
            ssh-add -l && composer2 "$@"
    # If "npm" is used, run npm
    # from our node container
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            silverstripe \
            npm "$@"
    # If "yarn" is used, run yarn
    # from our node container
    elif [ "$1" == "yarn" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            silverstripe \
            yarn "$@"
        $COMPOSE run --rm \
            -w /var/www/html \
            silverstripe \
            chmod 777 -R node_modules
    elif [ "$1" == "importdb" ]; then
        echo "Please enter the name of the database:"
        read DATABASE_NAME  

        echo "Please enter the name of the SQL to import:"
        read SQLFILE  

        echo "Importing the contents of $SQLFILE into the $DATABASE_NAME database."
        docker-compose exec -T silverstripe mysql -hdatabase -uroot $DATABASE_NAME < $SQLFILE
        echo "Database imported successfully."
    elif [ "$1" == "exportdb" ]; then
        echo "Please enter the name of the database to export:"
        read DATABASE_NAME  
        echo "Please enter the name of the SQL file to export to (i.e db.sql):"
        read SQLFILE

        echo "Exporting the contents of the $DATABASE_NAME database to $SQLFILE."
        docker-compose exec -T silverstripe mysqldump -hdatabase -uroot $DATABASE_NAME > $SQLFILE
        echo "Database exported successfully."
    # Else, pass-thru args to docker-compose
    else
        $COMPOSE "$@"
    fi

    if [ "$1" == "composer" ] || [ "$1" == "composer1" ] || [ "$1" == "composer2" ]; then
        # Change the owner / permissions of the vendor file from root
        $COMPOSE run --rm \
            -w /var/www/html \
            silverstripe \
            chown -R www-data:www-data vendor
        $COMPOSE run --rm \
            -w /var/www/html \
            silverstripe \
            chmod 777 -R vendor
    fi
else
    # Use the docker-compose ps command if nothing else passed through
    $COMPOSE ps
fi
